accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, BlogCreateView, BlogEditView, BlogDeleteView, \
    BlogCinemaView, BlogMusicView, BlogMemView, BlogMakersView, BlogNewsView, ProfileView, EditProfileView

urlpatterns = [
    path('', BlogListView.as_view(), name='home'),
    path('post/<int:pk>/', BlogDetailView.as_view(), name='post_detail'),
    path('new/', BlogCreateView.as_view(), name='post_new'),
    path('post/<int:pk>/edit/', BlogEditView.as_view(), name='post_edit'),
    path('post/<int:pk>/delete/', BlogDeleteView.as_view(), name='post_delete'),
    path('cinema/', BlogCinemaView.as_view(), name='cinema'),
    path('music/', BlogMusicView.as_view(), name='music'),
    path('mem/', BlogMemView.as_view(), name='mem'),
    path('makers/', BlogMakersView.as_view(), name='makers'),
    path('news/', BlogNewsView.as_view(), name='news'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('edit/', EditProfileView.as_view(), name='edit_profile'),
]

blog_project/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('blog.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


GENDER_CHOICES = [
    ['male', u"Мужской"],
    ['female', u"Женский"],
]

REL_CHOICES = [
    ['none', u"Не определенно"],
    ['single', u"Холост"],
    ['in_a_rel', u"В отношениях"],
    ['engaged', u"Помолвлен(а)"],
    ['married', u"Женат/Замужем"],
    ['in_love', u"Влюблен(а)"],
    ['complicated', u"Все сложно"],
]


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name=u"Пользователь")
    # username = models.CharField(max_length=30, blank=True, null=True, verbose_name=u"Полное имя")
    avatar = models.ImageField(upload_to='')
    bio = models.TextField(max_length=500, blank=True, null=True, verbose_name=u"О себе")
    city = models.CharField(max_length=30, blank=True, null=True, verbose_name=u"Город")
    # birth_date = models.DateField(null=True, blank=True, verbose_name=u"Дата рождения")
    gender = models.CharField(max_length=10, verbose_name=u"Пол", choices=GENDER_CHOICES, default="male")
    relationship = models.CharField(max_length=20, verbose_name=u"Статус отношений", choices=REL_CHOICES, default="none")




class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    body = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

blog/forms.py
from django import forms
from blog.models import Profile

class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        exclude = ['user']

class RegisterForm(forms.Form):
    username = forms.CharField(label=u"Имя пользователя")
    first_name = forms.CharField(label=u"Имя")
    last_name = forms.CharField(label=u"Фамилия")
    email = forms.EmailField(label=u"Email", required=False)
    password = forms.CharField(label=u"Пароль", widget=forms.PasswordInput)
    password_confirm = forms.CharField(label=u"Подтвердите пароль", widget=forms.PasswordInput)

    def is_valid(self):
        valid = super(RegisterForm, self).is_valid()
        if self.cleaned_data['password'] != self.cleaned_data['password_confirm']:
            self.add_error("password_confirm", u"Пароли не совпадают")
            return False
        return valid

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

blog/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post, Profile
from django.views.generic import TemplateView
from django.shortcuts import redirect
from django.urls import reverse
from blog.forms import RegisterForm, ProfileForm
from django.shortcuts import render
from django.contrib import messages



class BlogListView(ListView):
    model = Post
    template_name = 'home.html'


class BlogDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'


class BlogCreateView(CreateView):
    model = Post
    template_name = 'post_new.html'
    fields = '__all__'


class BlogEditView(UpdateView):
    model = Post
    template_name = 'post_edit.html'
    fields = ['title', 'body']


class BlogDeleteView(DeleteView):
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('home')


class BlogCinemaView(TemplateView):
    model = Post
    template_name = 'cinema.html'
    success_url = reverse_lazy('home')


class BlogMusicView(TemplateView):
    model = Post
    template_name = 'music.html'
    success_url = reverse_lazy('home')


class BlogMemView(TemplateView):
    model = Post
    template_name = 'mem.html'
    success_url = reverse_lazy('home')


class BlogMakersView(TemplateView):
    model = Post
    template_name = 'makers.html'
    success_url = reverse_lazy('home')


class BlogNewsView(TemplateView):
    model = Post
    template_name = 'news.html'
    success_url = reverse_lazy('home')


class ProfileView(TemplateView):
    template_name = "profile.html"

    def dispatch(self, request, *args, **kwargs):
        if not Profile.objects.filter(user=request.user).exists():
            return redirect(reverse("edit_profile"))
        context = {
            'selected_user': request.user
        }
        return render(request, self.template_name, context)


class EditProfileView(TemplateView):
    template_name = "edit_profile.html"

    def dispatch(self, request, *args, **kwargs):
        form = ProfileForm(instance=self.get_profile(request.user))
        if request.method == 'POST':
            form = ProfileForm(request.POST, request.FILES, instance=self.get_profile(request.user))
            if form.is_valid():
                form.instance.user = request.user
                form.save()
                messages.success(request, u"Профиль успешно обновлен!")
                return redirect(reverse("profile"))
        return render(request, self.template_name, {'form': form})

    def get_profile(self, user):
        try:
            return user.profile
        except:
            return None

blog/templates/cinema.html
{% extends 'base.html' %}

{% block content %}
    <h1>Cinema.Kg</h1>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}</form>
    <iframe width="1000" height="620"  src="https://www.tvigle.ru/video/gubka-bob-3-trailer/" frameborder="0" allowfullscreen="0"></iframe>
{% endblock content %}

blog/templates/edit_profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="container content" style="text-align: center;">
        <div style="display: inline-block; width: 400px;">
            <h2>Редактировать профиль</h2>
            <form method="post" class="bootstrap-form" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-success" value="Сохранить">
            </form>
        </div>
    </div>
{% endblock %}

blog/templates/home.html
{% extends 'base.html' %}
{% block content %}
{% for post in object_list %}
<div class="post-entry">
    <h2><a href="{% url 'post_detail' post.pk %}">{{ post.title }}</a></h2>
    <p>{{ post.body }}</p>
</div>
{% endfor %}
{% endblock content %}

blog/templates/makers.html
{% extends 'base.html' %}

{% block content %}
    <h1>Makers</h1>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}</form>
    <iframe width="1000" height="800"  src="https://makers.kg/" frameborder="0" allowfullscreen="0"></iframe>
{% endblock content %}

blog/templates/mem.html
{% extends 'base.html' %}

{% block content %}
    <h1>Mem</h1>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}</form>
    <iframe width="1000" height="800"  src="http://1001mem.ru/" frameborder="0" allowfullscreen="0"></iframe>
{% endblock content %}

blog/templates/music.html
{% extends 'base.html' %}

{% block content %}
    <h1>Music</h1>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}</form>
    <iframe width="1000" height="800"  src="https://zvuk.com/" frameborder="0" allowfullscreen="0"></iframe>
{% endblock content %}

blog/templates/news.html
{% extends 'base.html' %}

{% block content %}
    <h1>News</h1>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}</form>
    <iframe width="1000" height="800"  src="https://kg.akipress.org/" frameborder="0" allowfullscreen="0"></iframe>
{% endblock content %}

blog/templates/post_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete post</h1>
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ post.title }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{% endblock content %}

blog/templates/post_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="post-entry">
    <h2>{{ post.title }}</h2>
    <p>{{ post.body }}</p>
</div>
<p><a class="btn btn-default" href="{% url 'post_edit' post.pk %}">Edit And Create</a></p>
    <p><a class="btn btn-default" href="{% url 'post_delete' post.pk %}">Delete Blog Post</a></p>
{% endblock content %}

blog/templates/post_edit.html
{% extends 'base.html' %}
{% block content %}
<h1>Edit post</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
{% endblock content %}

blog/templates/post_new.html
{% extends 'base.html' %}

{% block content %}
    <h1>New post</h1>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" />
    </form>
{% endblock content %}

blog/templates/profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="container content">
        <h2>{{ selected_user.get_full_name }}</h2>

        <div class="row" style="margin-left: 50px;">
            <div class="col5">
                {% if selected_user.profile.avatar.name %}
                    <img src="{{ selected_user.profile.avatar.url }}" class="avatar-img img-thumbnail">
                {% else %}
                    <img src="{% static 'img/user.jpg' %}" class="avatar-img img-thumbnail">
                {% endif %}
                <br>
                <br>
                {% if selected_user.id == user.id %}
                    <a href="{% url 'edit_profile' %}" class="btn btn-sm btn-info">Редактировать профиль</a>
                {% endif %}
            </div>
            <div class="col">
                <dl class="row">
                    <dt class="col-sm-3 text-right">Полное имя</dt>
                    <dd class="col-sm-9">{{ selected_user.get_full_name }}</dd>

                    <dt class="col-sm-3 text-right">Email</dt>
                    <dd class="col-sm-9">{{ selected_user.email }}</dd>

                    <dt class="col-sm-3 text-right">Город</dt>
                    <dd class="col-sm-9">{{ selected_user.profile.city }}</dd>

                    <dt class="col-sm-3 text-right">Дата рождения</dt>
                    <dd class="col-sm-9">{{ selected_user.profile.birth_date|date:"d M Y" }}</dd>

                    <dt class="col-sm-3 text-right">Пол</dt>
                    <dd class="col-sm-9">{{ selected_user.profile.get_gender_display }}</dd>

                    <dt class="col-sm-3 text-right">Статус отношений</dt>
                    <dd class="col-sm-9">{{ selected_user.profile.get_relationship_display }}</dd>

                    <dt class="col-sm-3 text-right">О себе</dt>
                    <dd class="col-sm-9"><em style="font-family: 'Times New Roman', serif;">{{ selected_user.profile.bio|linebreaks }}</em></dd>
                </dl>
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,
initial-scale=ǐ, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/\
bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81i\
uXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
    <title>{% block title %} liquid site {% endblock title %}</title>

</head>
    <link rel="stylesheet" href="registration/styles.css">
<body>
<nav class="navbar navbar-expand-md navbar-light bg-light mb-8">
    <a class="navbar-brand" href="#">Liquid site</a>
    <a class="navbar-brand" href="{% url 'home' %}">Blog</a>
    <a class="navbar-brand" href="{% url 'cinema' %}">Cinema</a>
    <a class="navbar-brand" href="{% url 'music' %}">Music</a>
    <a class="navbar-brand" href="{% url 'mem' %}">Mem</a>
    <a class="navbar-brand" href="{% url 'makers' %}">Makers</a>
    <a class="navbar-brand" href="{% url 'news' %}">News</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link dropdown-toggle" href="#" id="userMenu"
                   data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">
                    {{ user.username }}
                </a>
                <div class="dropdown-menu dropdown-menu-right"
                     aria-labelledby="userMenu">
                    <a class="dropdown-item"
                       href="{% url 'password_change'%}">Change password</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'logout' %}">
                        Log Out</a>
                    <a class="dropdown-item" href="http://127.0.0.1:8000/new/">
                        New post</a>
                    <a class="dropdown-item" href="{% url 'profile'%}">
                        My profile</a>
                    <nav class="navbar navbar-light bg-light">
                        <form class="form-inline">
                            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                        </form>
                    </nav>
                </div>
            </li>
        </ul>
        {% else %}
        <form class="form-inline ml-auto">
            <a href="{% url 'login' %}" class="btn btn-outline-secondary">
                Log In</a>
            <a href="{% url 'signup' %}" class="btn btn-primary ml-2">
                Sign up</a>
        </form>
        {% endif %}
    </div>

</nav>
<div class="container">
    {% block content %}
    {% endblock content %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4\
YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/\
1.14.3/
umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbB\
JiSnjAK/
l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/\
js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ\
6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
<!--        <video width="900" height="700" controls="controls" src="%5Bnamba.kg%5D16291781.flv"></video>-->
<!--        <iframe width="1900" height="900" src="https://www.tvigle.ru/video/gubka-bob-3-trailer/" frameborder="0" allowfullscreen="2"></iframe>-->
</body>

templates/signup.html
{% extends 'base.html' %}

{% block content %}
<h2>Sign up</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
</form>
{% endblock content %}